# Generated by Django 4.1.2 on 2023-01-12 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentCd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_cd', models.CharField(help_text='부서코드', max_length=10, unique=True)),
                ('dept_nm', models.CharField(blank=True, help_text='부서이름', max_length=30, null=True)),
                ('senior_dept_cd', models.CharField(blank=True, help_text='상급부서 코드', max_length=10, null=True)),
                ('create_dt', models.DateTimeField(auto_now_add=True, help_text='등록일')),
                ('modify_dt', models.DateTimeField(auto_now=True, help_text='수정일')),
            ],
            options={
                'db_table': 'department_cd',
            },
        ),
        migrations.CreateModel(
            name='PositionCd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_cd', models.CharField(help_text='직책 코드', max_length=10, unique=True)),
                ('position_nm', models.CharField(help_text='직책 이름', max_length=20, null=True)),
                ('create_dt', models.DateTimeField(auto_now_add=True, help_text='등록일')),
                ('modify_dt', models.DateTimeField(auto_now=True, help_text='수정일')),
            ],
            options={
                'db_table': 'position_cd',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mem_id', models.CharField(help_text='사원번호', max_length=10, unique=True)),
                ('mem_name', models.CharField(help_text='사원이름', max_length=10, null=True)),
                ('mem_birth', models.DateTimeField(help_text='생년월일', null=True)),
                ('mem_mail_addr', models.EmailField(help_text='이메일', max_length=100, null=True, unique=True)),
                ('mem_phone', models.CharField(help_text='전화번호', max_length=13, null=True)),
                ('acc_recorder_id', models.CharField(help_text='출입기록 단말기 아이디', max_length=10, unique=True)),
                ('create_dt', models.DateTimeField(auto_now_add=True, help_text='등록일')),
                ('modify_dt', models.DateTimeField(auto_now=True, help_text='수정일')),
                ('join_dt', models.DateTimeField(help_text='입사일', null=True)),
                ('resign_dt', models.DateTimeField(help_text='퇴사일', null=True)),
                ('dept_cd', models.ForeignKey(blank=True, help_text='부서코드', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Member', to='members.departmentcd')),
                ('position_cd', models.ForeignKey(blank=True, help_text='직책코드', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Member', to='members.positioncd')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_user_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'member',
            },
        ),
    ]
