# Generated by Django 4.1.2 on 2022-12-08 12:03

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_remove_member_mem_pwd'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='member',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
