# Generated by Django 4.1.2 on 2022-12-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_member_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='auth_cd',
            field=models.CharField(max_length=10, null=True, verbose_name='권한코드'),
        ),
        migrations.AlterField(
            model_name='member',
            name='join_dt',
            field=models.DateTimeField(null=True, verbose_name='입사일'),
        ),
        migrations.AlterField(
            model_name='member',
            name='mem_birth',
            field=models.DateTimeField(null=True, verbose_name='생년월일'),
        ),
        migrations.AlterField(
            model_name='member',
            name='mem_mail_addr',
            field=models.EmailField(max_length=100, null=True, unique=True, verbose_name='이메일'),
        ),
        migrations.AlterField(
            model_name='member',
            name='mem_name',
            field=models.CharField(max_length=10, null=True, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='member',
            name='mem_phone',
            field=models.CharField(max_length=13, null=True, verbose_name='전화번호'),
        ),
        migrations.AlterField(
            model_name='member',
            name='position_cd',
            field=models.CharField(max_length=10, null=True, verbose_name='직책코드'),
        ),
        migrations.AlterField(
            model_name='member',
            name='resign_dt',
            field=models.DateTimeField(null=True, verbose_name='퇴사일'),
        ),
        migrations.AlterField(
            model_name='member',
            name='team_cd',
            field=models.CharField(max_length=10, null=True, verbose_name='팀 코드'),
        ),
    ]
